name: intl_phone_field_custom
description: A customised Flutter TextFormField to input international phone number along with country code.
version: 3.3.0
homepage: https://github.com/payungsak-nano/intl_phone_field_custom

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  test: ^1.17.12

flutter:
  assets:
    - assets/flags/
